export type { WidgetProps } from './WidgetBase'
export { PlaceholderWidget } from './PlaceholderWidget'
export { WeatherWidget } from './WeatherWidget'
export type { WeatherConfig, WeatherData } from './WeatherWidget'
export { ScriptWidget } from './ScriptWidget'
export type { ScriptConfig } from './ScriptWidget'
